spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://localhost:3306/base_core?createDatabaseIfNotExist=true
    username: root
    password: mapyeugau110418
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret:
    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
  expired:
    access: 86400000

  mail:
    host: smtp.gmail.com
    port: 587
    username: thaingocphat231@gmail.com
    password: "qora aght jalw asiv"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
